### PR TITLE
the front end already done

### PR DESCRIPTION
**Pull request by aldoprogrammer**
## Related Issue(s)

[//]: # ([Cite any related issue&#40;s&#41; or feature request&#40;s&#41; from the repository's issue tracker.])
Fixes #
For #

## Proposed Changes

[//]: # ([List down the specific changes you have made in this pull request.])

- [x]
- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## To-Do

- [ ]

### CODE REVIEW

**Review by jaysilver-5 — COMMENTED** [review]
Your code should be a continuation of the main repo. Setup the project before making your changes and don't initialize a totally new project. You initialized a react app inside of a next.js app. We are using tailwind, typescript and pnpm for package management. You did a good job but with vanilla execution.

**Comment by Nasfame** [comment]
@aldoprogrammer Declining this PR due to 

1. Unnecessary changes - framework migrated to React.
2. We strictly write code in TS.


@aldoprogrammer Create a new branch from main. We have give u write access to our repo . 
https://github.com/learnery-engine/creator.learnery/invitations


Raise a fresh pr with necessary changes

**Comment by aldoprogrammer** [comment]
`Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.`  i dont have access to this https://github.com/learnery-engine/creator.learnery/invitations.

And yah I will make another one soon using Next JS and typscript, thanks for the advice.

**Comment by aldoprogrammer** [comment]
Suree, I will work on the project today

**Comment by Nasfame** [comment]
Ok

**Pull request closed without merging**
